from pathlib import Path
p=Path('/mnt/data/gfix5/videogame_engine.py')
s=p.read_text()
old='''                "face_twist": residue_to_bipolar(_residue(self.seed, f"face_twist:{i}")),\n            })\n'''
new='''                "face_twist": residue_to_bipolar(_residue(self.seed, f"face_twist:{i}")),\n                # Algorithm-span coordinates.  z_step is a discrete phase on\n                # the same cyclic lattice as the writer's pattern length.\n                # Linkage is therefore permitted by congruence, not merely by\n                # geometric proximity.  This keeps visual topology coupled to\n                # the written step algorithm while remaining deterministic.\n                "pattern_length": 16,\n                "z_step": int(i * 7 + math.floor(32.0 * _residue(self.seed, f"zstep:{i}"))),\n            })\n'''
assert old in s
s=s.replace(old,new,1)
old2='''        self.scene._engine_mask = dict(self.engine_mask)\n        # Playlist / step-algo / composition fingerprints tilt which book fractal\n'''
new2='''        self.scene._engine_mask = dict(self.engine_mask)\n        # Carry the writer's actual pattern-length lattice into the scenograph.\n        # Never use Python's process-salted hash for this mapping.\n        try:\n            pl = self.id.get("pattern_lengths") or {}\n            if isinstance(pl, dict):\n                vals = [max(1, int(v)) for _, v in sorted(pl.items(), key=lambda kv: str(kv[0]))]\n            elif isinstance(pl, (list, tuple)):\n                vals = [max(1, int(v)) for v in pl]\n            else:\n                vals = []\n        except Exception:\n            vals = []\n        if not vals:\n            vals = [16]\n        self.scene._algorithm_pattern_lengths = tuple(vals)\n        for _i, _layer in enumerate(self.scene.layers):\n            _plen = self.scene._algorithm_pattern_lengths[_i % len(self.scene._algorithm_pattern_lengths)]\n            _layer["pattern_length"] = _plen\n            # Scale the discrete Z phase to the writer span.  The residue is\n            # deterministic; the modulo makes it a true cyclic pattern phase.\n            _raw = int(_layer.get("z_step", 0))\n            _layer["z_step"] = _raw % _plen\n            _layer["pattern_span"] = _plen\n        # Playlist / step-algo / composition fingerprints tilt which book fractal\n'''
assert old2 in s
s=s.replace(old2,new2,1)
# replace linkage function body sections with congruence helpers inserted after n
old3='''            n=len(nodes)\n            # Sparse stochastic-looking strokes: long, medium and micro links.\n            seg_prob = 0.34 if not goava else 0.58\n'''
new3='''            n=len(nodes)\n            meta = []\n            for i, L in enumerate(layers):\n                plen = max(1, int(L.get("pattern_length", 16) or 16))\n                zstep = int(L.get("z_step", i * 7)) % plen\n                meta.append((plen, zstep))\n\n            def _z_congruent(i, j, tolerance=0):\n                """Return whether two written algorithm phases may be linked.\n\n                The congruence is evaluated on the greatest-common-divisor\n                lattice.  Different pattern lengths therefore share links only\n                at compatible Z phases; longer algorithm spans do not erase the\n                phase relationship.  A small deterministic tolerance is used for\n                faces spanning three different pattern lengths.\n                """\n                pi, zi = meta[i]; pj, zj = meta[j]\n                g = math.gcd(pi, pj)\n                if ((zi - zj) % g) <= tolerance:\n                    return True\n                # Scale to the common algorithm span.  This second test permits\n                # exact rational phase correspondence when lengths differ.\n                return ((zi * pj - zj * pi) % math.lcm(pi, pj)) == 0\n\n            def _link_score(i, j):\n                pi, zi = meta[i]; pj, zj = meta[j]\n                span = math.lcm(pi, pj)\n                congr = 1.0 if _z_congruent(i, j) else 0.0\n                # Near phases on a shared span get a softer chance, while a\n                # broken congruence remains genuinely breakable.\n                dz = abs((zi * pj - zj * pi) % span)\n                dz = min(dz, span - dz)\n                phase = 1.0 - (dz / max(1.0, span * 0.5))\n                return 0.72 * congr + 0.28 * max(0.0, phase)\n\n            # Sparse stochastic-looking strokes: long, medium and micro links.\n            # Their existence is filtered by algorithmic Z-step congruence.\n            seg_prob = 0.30 if not goava else 0.54\n'''
assert old3 in s
s=s.replace(old3,new3,1)
old4='''                    q=self._rng(f"link:segment:{i}:{j}")\n                    if q > seg_prob:\n                        continue\n'''
new4='''                    q=self._rng(f"link:segment:{i}:{j}")\n                    compat = _link_score(i, j)\n                    # Congruence is a gate, not decoration: incompatible Z-step\n                    # phases are broken before geometric drawing is considered.\n                    if not _z_congruent(i, j):\n                        continue\n                    if q > seg_prob * (0.55 + 0.45 * compat):\n                        continue\n'''
assert old4 in s
s=s.replace(old4,new4,1)
old5='''                        q=self._rng(f"link:face:{i}:{j}:{k}")\n                        if q > face_prob:\n                            continue\n'''
new5='''                        q=self._rng(f"link:face:{i}:{j}:{k}")\n                        congr = (_z_congruent(i, j) and _z_congruent(j, k) and _z_congruent(i, k))\n                        if not congr:\n                            continue\n                        compat = (_link_score(i, j) + _link_score(j, k) + _link_score(i, k)) / 3.0\n                        if q > face_prob * (0.52 + 0.48 * compat):\n                            continue\n'''
assert old5 in s
s=s.replace(old5,new5,1)
p.write_text(s)
